# Text Analysis with Deep Learning
#### Word2Vec of Gensim
##### prepared by Chao-Lin Liu
實際執行 simple.word2vec.ipynb，觀察和比較設定不同 seed 的時候所得到的 word vectors 和 most_similar 詞彙

In [2]:
import numpy as np
import nltk
import warnings
warnings.filterwarnings(action='ignore', category=UserWarning, module='gensim')
from gensim.models import Word2Vec

In [4]:
from nltk.corpus import brown
sentences = brown.sents()
"""nltk.download('brown')
sentences = nltk.brown.sents()"""

In [5]:
len(sentences)

57340

In [6]:
print(sentences[0])

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', "Atlanta's", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', "''", 'that', 'any', 'irregularities', 'took', 'place', '.']


# NO SEED 

In [13]:
model = Word2Vec(sentences, size=10, window=5, min_count=5, workers=4)
word = sentences[0][2]
print(word)
model.wv[word]

County


array([ 0.65429693, -0.07984881,  2.0935822 ,  0.24326402, -1.4334669 ,
        0.6531443 , -0.23059085, -0.17957392,  0.430512  ,  0.2892541 ],
      dtype=float32)

In [20]:
model = Word2Vec(sentences, size=10, window=5, min_count=5, workers=4)
word = sentences[0][2]
print(word)
model.wv[word]

County


array([ 0.36342672, -0.14834179,  2.1629977 ,  0.18508191, -1.2519689 ,
        0.7949608 , -0.42402762, -0.20449197,  0.5653986 ,  0.34473264],
      dtype=float32)

In [21]:
model = Word2Vec(sentences, size=10, window=5, min_count=5, workers=4)
word = sentences[0][2]
print(word)
model.wv[word]

County


array([ 0.36190233, -0.14801641,  2.1632452 ,  0.18438667, -1.251293  ,
        0.7943459 , -0.42399263, -0.20529467,  0.5652424 ,  0.34495622],
      dtype=float32)

# SET SEED 

In [ ]:
def Seed10():
    model = Word2Vec(sentences, size=10, window=5, min_count=5, seed=1, workers=4)
    word = sentences[0][2]
    print(model.wv[word])
    print(model.wv.most_similar(positive=['king', 'woman'], negative=['man']))
    print(model.wv.most_similar(positive='woman', topn=6))
Seed10()
Seed10()

In [ ]:
def Seed100():
    model = Word2Vec(sentences, size=100, window=5, min_count=5, seed=1, workers=4)
    word = sentences[0][2]
    print(model.wv[word])
    print(model.wv.most_similar(positive=['king', 'woman'], negative=['man']))
    print(model.wv.most_similar(positive='woman', topn=6))
Seed100()
Seed100()